"""Add user_notes and admin_notes to timesheets

Revision ID: 13fe1c13ccd1
Revises: 001_initial_schema
Create Date: 2026-01-06 21:30:39.186470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13fe1c13ccd1'
down_revision = '001_initial_schema'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_notes', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('admin_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheets', schema=None) as batch_op:
        batch_op.drop_column('admin_notes')
        batch_op.drop_column('user_notes')

    # ### end Alembic commands ###
